# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CN8Yw_vN4xepVss99iPL4vvI-9Ybyb9j
"""

# Install OpenCV
!pip install opencv-python-headless --quiet
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import os

# Step 1: Upload dataset (individual image files)
print("Upload individual image files for the dataset (e.g., 'image1.jpg', 'image2.png'):")
uploaded = files.upload()

# Step 2: Save the uploaded dataset images to a directory
dataset_path = "dataset_images"
os.makedirs(dataset_path, exist_ok=True)
for fname, content in uploaded.items():
    with open(os.path.join(dataset_path, fname), 'wb') as f:
        f.write(content)

# Step 3: Upload query image
print("Upload a query image (e.g., 'query.jpg'):")
uploaded_query = files.upload()
query_path = list(uploaded_query.keys())[0]

# Step 4: Histogram extraction function
def get_histogram(img):
    hist = cv2.calcHist([img], [0, 1, 2], None, [8, 8, 8], [0, 256, 0, 256, 0, 256])
    cv2.normalize(hist, hist)
    return hist.flatten()

# Step 5: Read query image and extract histogram
query = cv2.imread(query_path)
query = cv2.resize(query, (200, 200)) # Resize for consistency
query_hist = get_histogram(query)

# Step 6: Compare with dataset images
scores = []
for file in os.listdir(dataset_path):
    if file.lower().endswith(('.jpg', '.jpeg', '.png')):
        image_path = os.path.join(dataset_path, file)
        image = cv2.imread(image_path)
        image = cv2.resize(image, (200, 200))
        hist = get_histogram(image)
        score = cv2.compareHist(query_hist, hist, cv2.HISTCMP_CORREL)
        scores.append((score, file, image))

# Step 7: Show top 3 matching images
scores.sort(reverse=True)
top_matches = scores[:3]
print("Top 3 Matching Images:")

plt.figure(figsize=(12, 6))
# Show query image
plt.subplot(1, 4, 1)
plt.imshow(cv2.cvtColor(query, cv2.COLOR_BGR2RGB))
plt.title("Query Image")
plt.axis('off')

# Show top 3 results
for i, (score, fname, img) in enumerate(top_matches):
    plt.subplot(1, 4, i + 2)
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(f"Match {i+1}\nScore: {score:.2f}")
    plt.axis('off')
plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files
import os

# Function to extract a color histogram from an image in HSV color space
def extract_color_histogram(image, bins=(8, 8, 8)):
    if image is None: # Check if image loaded successfully
        raise ValueError("Image is empty, cannot extract features.")
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV) # Convert BGR to HSV
    # Compute 3D histogram for H, S, and V channels
    hist = cv2.calcHist([hsv], [0, 1, 2], None, bins, [0,180, 0,256, 0,256])
    return hist.flatten() # Flatten to 1D array for similarity comparison

# Upload query image
print("Please upload a query image:")
uploaded_query = files.upload()
query_image_filename = list(uploaded_query.keys())[0]
img = cv2.imread(query_image_filename)

# Ensure query image is loaded
if img is None:
    print(f"Error: Could not load query image '{query_image_filename}'. Please ensure the file exists and is a valid image.")
else:
    query_features = extract_color_histogram(img) # Extract histogram features of query image

    # Upload dataset images (candidate matches)
    print("Please upload all dataset images you want to compare (e.g., 'image1.jpg', 'image2.png'):")
    uploaded_dataset = files.upload()

    dataset = []
    dataset_filenames = []

    # Load dataset images based on uploaded files
    for filename, content in uploaded_dataset.items():
        # Save the uploaded file to disk to be read by cv2.imread
        with open(filename, 'wb') as f:
            f.write(content)
        loaded_img = cv2.imread(filename)
        if loaded_img is not None:
            dataset.append(loaded_img)
            dataset_filenames.append(filename)
        else:
            print(f"Warning: Could not load dataset image '{filename}'. Please ensure it's a valid image file.")

    if not dataset: # If no dataset images were loaded
        print("Error: No valid dataset images were loaded. Aborting feature extraction and comparison.")
    else:
        # Extract histogram features for all dataset images
        dataset_features = [extract_color_histogram(image) for image in dataset]

        # Compute cosine similarity between query image and each dataset image
        similarities = [cosine_similarity([query_features], [features])[0][0] for features in dataset_features]

        # Rank images based on similarity score (higher is more similar)
        ranked_indices = sorted(range(len(similarities)), key=lambda i: similarities[i], reverse=True)

        # Display the query image
        plt.figure()
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB)) # Convert BGR to RGB for matplotlib
        plt.title('Query Image')
        plt.axis('off')
        plt.show()

        # Display top-k similar images from the dataset
        top_k = min(3, len(dataset))
        for i in range(top_k):
            similar_img = dataset[ranked_indices[i]]
            plt.figure()
            plt.imshow(cv2.cvtColor(similar_img, cv2.COLOR_BGR2RGB))
            plt.title(f"Similar Image {i+1} ({dataset_filenames[ranked_indices[i]]})")
            plt.axis('off')
            plt.show()

# Install required libraries
    !pip install opencv-python-headless scikit-image --quiet
    import cv2
    import numpy as np
    import matplotlib.pyplot as plt
    from skimage.feature import local_binary_pattern
    from google.colab import files
    import os

    # Step 1: Upload individual image files for the dataset
    print("Upload individual image files for the dataset (e.g., 'image1.jpg', 'image2.png'):")
    uploaded_dataset = files.upload()

    dataset_path = "texture_dataset"
    os.makedirs(dataset_path, exist_ok=True)

    # Save the uploaded dataset images to a directory
    for fname, content in uploaded_dataset.items():
        with open(os.path.join(dataset_path, fname), 'wb') as f:
            f.write(content)

    # Step 2: Upload query image
    print("Upload a query texture image (e.g., 'query.jpg'):")
    uploaded_query = files.upload()
    query_img_path = list(uploaded_query.keys())[0]
    # Step 3: LBP feature extraction function
    def extract_lbp_features(gray_img):
        lbp = local_binary_pattern(gray_img, P=24, R=3, method="uniform")
        hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, 27), range=(0, 26))
        hist = hist.astype("float")
        hist /= (hist.sum() + 1e-6)
        return hist
    # Step 4: Extract LBP features from query image
    query_img = cv2.imread(query_img_path, cv2.IMREAD_GRAYSCALE)
    query_img = cv2.resize(query_img, (256, 256)) # Resize for consistency
    query_hist = extract_lbp_features(query_img)
    # Step 5: Compare with dataset images using Chi-square distance
    def chi2_distance(histA, histB, eps=1e-6):
        return 0.5 * np.sum(((histA - histB) ** 2) / (histA + histB + eps))
    scores = []
    for file in os.listdir(dataset_path):
        if file.lower().endswith(('.jpg', '.jpeg', '.png', '.avif')):
            img_path = os.path.join(dataset_path, file)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, (256, 256))
            hist = extract_lbp_features(img)
            dist = chi2_distance(query_hist, hist)
            scores.append((dist, file, img))
    # Step 6: Display top 3 matches
    scores.sort(key=lambda x: x[0]) # lower distance = better match
    top_matches = scores[:3]
    plt.figure(figsize=(12, 6))
    plt.subplot(1, 4, 1)
    plt.imshow(query_img, cmap='gray')
    plt.title("Query Image")
    plt.axis('off')
    for i, (dist, fname, img) in enumerate(top_matches):
        plt.subplot(1, 4, i + 2)
        plt.imshow(img, cmap='gray')
        plt.title(f"Match {i+1}\nDist: {dist:.2f}")
        plt.axis('off')
    plt.tight_layout()
    plt.show()

# Install required packages
!pip install opencv-python-headless --quiet
!pip install scikit-learn --quiet
from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
import os

# Upload query image
print("Upload the query image:")
uploaded_query = files.upload()
query_path = list(uploaded_query.keys())[0]

# Upload dataset images
print("Upload dataset images (upload multiple files):")
uploaded_dataset = files.upload()

# Function to extract color histogram (for fashion images)
def extract_color_histogram(image, bins=(8, 8, 8)):
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    hist = cv2.calcHist([hsv], [0, 1, 2], None, bins, [0,180, 0,256, 0,256])
    cv2.normalize(hist, hist)
    return hist.flatten()

# Function to extract grayscale histogram (for medical images)
def extract_gray_histogram(image, bins=256):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    hist = cv2.calcHist([gray], [0], None, [bins], [0, 256])
    cv2.normalize(hist, hist)
    return hist.flatten()

# Load query image
query_img = cv2.imread(query_path)

if query_img is None:
    print(f"Error: Could not load query image '{query_path}'. This might be due to an unsupported format like .avif. Consider installing 'Pillow-AVIF' and using Pillow to load it first, then convert to OpenCV format.")
    raise ValueError("Query image could not be loaded.")

# For Fashion E-Commerce, use color histogram:
query_features_fashion = extract_color_histogram(query_img)

# For Medical Imaging, use grayscale histogram:
query_features_medical = extract_gray_histogram(query_img)

# Load dataset images
dataset_imgs = []
dataset_fashion_features = []
dataset_medical_features = []
valid_dataset_filenames = []

for filename in uploaded_dataset.keys():
    img = cv2.imread(filename)
    if img is None:
        print(f"Warning: Could not load dataset image '{filename}'. Skipping. This might be due to an unsupported format like .avif.")
        continue
    dataset_imgs.append(img)
    valid_dataset_filenames.append(filename)
    dataset_fashion_features.append(extract_color_histogram(img))
    dataset_medical_features.append(extract_gray_histogram(img))

if not dataset_imgs:
    print("Error: No valid dataset images were loaded. Aborting comparison.")
    raise ValueError("No valid dataset images.")

# Choose mode: 'fashion' or 'medical'
mode = 'fashion' # change to 'medical' for medical images
if mode == 'fashion':
    query_features = query_features_fashion
    dataset_features = dataset_fashion_features
elif mode == 'medical':
    query_features = query_features_medical
    dataset_features = dataset_medical_features

# Calculate cosine similarity scores
similarities = [cosine_similarity([query_features], [feat])[0][0] for feat in dataset_features]

# Sort by similarity descending
ranked_indices = sorted(range(len(similarities)), key=lambda i: similarities[i], reverse=True)

# Display query image
plt.figure(figsize=(5,5))
plt.imshow(cv2.cvtColor(query_img, cv2.COLOR_BGR2RGB))
plt.title('Query Image')
plt.axis('off')
plt.show()

# Display top 3 similar images
top_k = 3
for i in range(min(top_k, len(dataset_imgs))):
    idx = ranked_indices[i]
    plt.figure(figsize=(5,5))
    plt.imshow(cv2.cvtColor(dataset_imgs[idx], cv2.COLOR_BGR2RGB))
    plt.title(f"Similar Image {i+1} (Score: {similarities[idx]:.2f})")
    plt.axis('off')
    plt.show()

import os
# Install required packages
!pip install opencv-python-headless --quiet
!pip install scikit-learn --quiet
from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity

# Upload query image
print("Upload the query image:")
uploaded_query = files.upload()
query_path = list(uploaded_query.keys())[0]

# Upload dataset images
print("Upload dataset images (upload multiple files):")
uploaded_dataset = files.upload()

# Function to extract color histogram (for fashion images)
def extract_color_histogram(image, bins=(8, 8, 8)):
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    hist = cv2.calcHist([hsv], [0, 1, 2], None, bins, [0,180, 0,256, 0,256])
    cv2.normalize(hist, hist)
    return hist.flatten()

# Function to extract grayscale histogram (for medical images)
def extract_gray_histogram(image, bins=256):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    hist = cv2.calcHist([gray], [0], None, [bins], [0, 256])
    cv2.normalize(hist, hist)
    return hist.flatten()

# Load query image
query_img = cv2.imread(query_path)

# Check if query image was loaded successfully
if query_img is None:
    print(f"Error: Could not load query image from {query_path}")
    # Optionally, raise an error or exit
    raise FileNotFoundError(f"Query image not found or could not be loaded: {query_path}")

# For Fashion E-Commerce, use color histogram:
query_features_fashion = extract_color_histogram(query_img)

# For Medical Imaging, use grayscale histogram:
query_features_medical = extract_gray_histogram(query_img)

# Load dataset images
dataset_imgs = []
dataset_fashion_features = []
dataset_medical_features = []

for filename in uploaded_dataset.keys():
    img = cv2.imread(filename)
    if img is None:
        print(f"Warning: Could not load dataset image from {filename}. Skipping.")
        continue
    dataset_imgs.append(img)
    dataset_fashion_features.append(extract_color_histogram(img))
    dataset_medical_features.append(extract_gray_histogram(img))

# Check if any dataset images were loaded
if not dataset_imgs:
    print("Error: No valid dataset images were loaded. Cannot proceed with similarity comparison.")
    # Optionally, raise an error or exit
    raise ValueError("No dataset images loaded.")

# Choose mode: 'fashion' or 'medical'
mode = 'fashion' # change to 'medical' for medical images

if mode == 'fashion':
    query_features = query_features_fashion
    dataset_features = dataset_fashion_features
elif mode == 'medical':
    query_features = query_features_medical
    dataset_features = dataset_medical_features

# Calculate cosine similarity scores
similarities = [cosine_similarity([query_features], [feat])[0][0] for feat in dataset_features]

# Sort by similarity descending
ranked_indices = sorted(range(len(similarities)), key=lambda i: similarities[i], reverse=True)

# Display query image
plt.figure(figsize=(5,5))
plt.imshow(cv2.cvtColor(query_img, cv2.COLOR_BGR2RGB))
plt.title('Query Image')
plt.axis('off')
plt.show()

# Display top 3 similar images
top_k = 3
for i in range(min(top_k, len(dataset_imgs))):
    idx = ranked_indices[i]
    plt.figure(figsize=(5,5))
    plt.imshow(cv2.cvtColor(dataset_imgs[idx], cv2.COLOR_BGR2RGB))
    plt.title(f"Similar Image {i+1} (Score: {similarities[idx]:.2f})")
    plt.axis('off')
    plt.show()